In [ ]:
import cv2,numpy
face_cascade =cv2.CascadeClassifier(r"C:\Users\OM\Desktop\data science project\face detection\haarcascade_frontalface_default.xml")
img=cv2.imread(r"C:\Users\OM\Desktop\data science project\face detection\11.jpg")
gray_img =cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces=face_cascade.detectMultiScale(gray_img,scaleFactor=1.3,minNeighbors=5)

print(type(faces))
print(faces)

for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0), 3)
    cv2.imshow("face detection", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[253   5  56  56]
 [371 154  49  49]
 [486 142  58  58]
 [595 155  76  76]
 [305 265  57  57]
 [732 171  52  52]
 [517 276  58  58]
 [ 77 167  58  58]
 [659 177  58  58]
 [428 375  59  59]
 [648 378  58  58]
 [348 399  53  53]
 [561  38  51  51]
 [457  40  50  50]
 [194 280  64  64]
 [612 207  54  54]
 [218 454  53  53]
 [ 50 328  53  53]]
